python3.pkgs.sphinxemoji: Fix missing propagated dependency on "setuptools"
That oversight caused following error when building "python3.pkgs.sphinx-notfound-page"

     File "/nix/store/1l5mygrbwwcr9d15wh0bd593pzdbng68-python3.11-sphinx-7.2.6/lib/python3.11/site-packages/sphinx/registry.py", line 447, in load_extension
        mod = import_module(extname)
              ^^^^^^^^^^^^^^^^^^^^^^
      File "/nix/store/asiphbpiy2gmidfm3xbwcikayhs66289-python3-3.11.7/lib/python3.11/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
      File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 940, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/nix/store/5bng03b1dcf3qxbhil9b2f46yh2m3wvb-python3.11-sphinxemoji-0.2.0/lib/python3.11/site-packages/sphinxemoji/sphinxemoji.py", line 3, in <module>
        from pkg_resources import resource_filename
    ModuleNotFoundError: No module named 'pkg_resources'